import type { Metadata } from "next"
import { cookies } from "next/headers"
import Link from "next/link"
import { notFound, redirect } from "next/navigation"
import { ArrowLeft, CalendarDays, MapPin, ShieldCheck } from "lucide-react"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { JV_COOKIE, validJvCookie } from "@/lib/jv-auth"
import { getJvBoxScore } from "@/lib/jv-stats"

export const dynamic = "force-dynamic"
type Props = { params: Promise<{ gameId: string }> }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const game = getJvBoxScore(Number((await params).gameId))
  if (!game) return { title: "Game not found | Hortonville JV Soccer" }
  return { title: `Hortonville ${game.team.goals}–${game.opponentTotals.goals} ${game.opponent} | JV Box Score`, robots: { index: false, follow: false } }
}

export default async function JvGamePage({ params }: Props) {
  const jar = await cookies()
  if (!validJvCookie(jar.get(JV_COOKIE)?.value)) redirect("/jv")
  const game = getJvBoxScore(Number((await params).gameId))
  if (!game) notFound()
  return <main id="main-content" className="min-h-screen bg-[#080c13] text-slate-100"><header className="border-b border-white/10 bg-[#080c13]/95"><div className="mx-auto flex min-h-18 max-w-6xl items-center justify-between px-5 py-4 lg:px-8"><Link href="/jv#schedule" className="flex items-center gap-2 text-sm font-semibold text-slate-400 hover:text-white"><ArrowLeft className="size-4" /> Season dashboard</Link><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.12em] text-slate-500"><ShieldCheck className="size-4 text-emerald-400" /> Private box score</div></div></header>
    <div className="mx-auto max-w-6xl px-5 pb-16 pt-9 lg:px-8"><section className="overflow-hidden rounded-[32px] border border-white/10 bg-[#0d131e]"><div className="border-b border-white/8 bg-gradient-to-br from-red-700/25 via-transparent to-transparent px-6 py-7 sm:px-10 sm:py-9"><div className="flex flex-wrap gap-5 text-xs font-semibold uppercase tracking-[.13em] text-slate-500"><span className="flex items-center gap-2"><CalendarDays className="size-4" />{formatDate(game.date)}</span><span className="flex items-center gap-2"><MapPin className="size-4" />{game.location}</span>{game.conference ? <span className="rounded-full bg-red-500/10 px-3 py-1 text-red-400">Conference</span> : null}</div><div className="mt-8 grid grid-cols-[1fr_auto_1fr] items-center gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-red-400">Hortonville</p><p className="mt-2 text-2xl font-black text-white sm:text-4xl">Polar Bears</p></div><div className="text-center"><p className="text-4xl font-black text-white sm:text-6xl">{game.team.goals}<span className="mx-2 text-slate-700">–</span>{game.opponentTotals.goals}</p><p className={`mx-auto mt-3 w-fit rounded-lg px-3 py-1 text-xs font-black ${game.result === "W" ? "bg-emerald-500/15 text-emerald-400" : "bg-red-500/15 text-red-400"}`}>FINAL · {game.result}</p></div><div className="text-right"><p className="text-xs font-bold uppercase tracking-[.18em] text-slate-500">Opponent</p><p className="mt-2 text-2xl font-black text-white sm:text-4xl">{game.opponent}</p></div></div></div>
      <div className="grid gap-8 p-6 sm:p-10 lg:grid-cols-[.9fr_1.1fr]"><div><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Match comparison</p><h2 className="mt-1 text-xl font-bold text-white">Team totals</h2><div className="mt-5 overflow-hidden rounded-2xl border border-white/8"><Comparison label="Goals" home={game.team.goals} away={game.opponentTotals.goals} /><Comparison label="Shots" home={game.team.shots} away={game.opponentTotals.shots} /><Comparison label="Shots on goal" home={game.team.sog} away="—" /><Comparison label="Saves" home={game.team.saves} away={game.opponentTotals.saves} /><Comparison label="Yellow cards" home={game.team.yc} away="—" /></div></div><div><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Goal log</p><h2 className="mt-1 text-xl font-bold text-white">Scoring summary</h2><div className="mt-5 space-y-2">{game.scoring.length ? game.scoring.map((goal,index) => <div key={`${goal.scorer}-${index}`} className="flex items-center gap-4 rounded-2xl border border-white/6 bg-white/[.025] p-4"><span className="grid size-9 place-items-center rounded-xl bg-red-600 text-sm font-black">{index + 1}</span><div><p className="font-bold text-white">{stripKey(goal.scorer)}</p><p className="text-xs text-slate-500">{goal.assist ? `Assist: ${stripKey(goal.assist)}` : "Unassisted"}</p></div><span className="ml-auto text-xs font-bold uppercase text-slate-500">{goal.half}</span></div>) : <div className="rounded-2xl border border-white/6 bg-white/[.025] p-5 text-sm text-slate-400">No Hortonville goals recorded.</div>}</div></div></div></section>
      <section className="mt-7 rounded-[28px] border border-white/10 bg-[#0d131e] p-5 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.16em] text-slate-500">Hortonville</p><h2 className="mt-1 text-xl font-bold text-white">Player box score</h2><div className="mt-5 overflow-x-auto"><Table><TableHeader><TableRow className="border-white/10 hover:bg-transparent"><TableHead className="text-slate-500">Player</TableHead>{["SH","SOG","G","A","YC","RC","SV","GK MIN"].map(label => <TableHead key={label} className="text-center text-slate-500">{label}</TableHead>)}</TableRow></TableHeader><TableBody>{game.players.map(player => <TableRow key={player.player} className="border-white/5"><TableCell className="font-semibold text-white">{stripKey(player.player)}</TableCell>{[player.shots,player.sog,player.goals,player.assists,player.yc,player.rc,player.saves,player.gkMinutes].map((value,index) => <TableCell key={index} className={`text-center ${value ? "font-bold text-white" : "text-slate-700"}`}>{value || "—"}</TableCell>)}</TableRow>)}</TableBody></Table></div></section>
    </div></main>
}

function Comparison({ label, home, away }: { label: string; home: number | string; away: number | string }) { return <div className="grid grid-cols-[1fr_1.5fr_1fr] items-center border-b border-white/6 px-4 py-3 last:border-0"><span className="text-center text-lg font-black text-white">{home}</span><span className="text-center text-xs font-semibold uppercase tracking-wider text-slate-500">{label}</span><span className="text-center text-lg font-black text-slate-400">{away}</span></div> }
function stripKey(value: string) { return value.replace(/^\d+\s*-\s*/, "") }
function formatDate(value: string) { return new Intl.DateTimeFormat("en-US", { month: "long", day: "numeric", year: "numeric", timeZone: "UTC" }).format(new Date(`${value}T00:00:00Z`)) }
