import type { Metadata } from "next"
import Image from "next/image"
import Link from "next/link"
import { cookies } from "next/headers"
import { notFound } from "next/navigation"
import { Navigation } from "@/components/navigation"
import { COACH_COOKIE, validCoachCookie } from "@/lib/coach-auth"
import { getScoutingReport } from "@/lib/scouting"
import { CoachLogin } from "../../login"

export const dynamic = "force-dynamic"
export const metadata: Metadata = { title:"Opponent report | Coach’s Corner", robots:{index:false,follow:false,nocache:true} }
export default async function ReportPage({params}:{params:Promise<{slug:string}>}) {
  if (!validCoachCookie((await cookies()).get(COACH_COOKIE)?.value)) return <><Navigation /><CoachLogin /></>
  const r=getScoutingReport((await params).slug)
  if(!r) notFound()
  const shutouts=r.matches.filter(m=>m.ga===0).length
  return <><div className="print:hidden"><Navigation /></div><main className="min-h-screen bg-[#f7f7f5] pb-16 print:bg-white"><header className="bg-neutral-950 text-white print:bg-white print:text-black"><div className="site-container py-10"><Link href="/coachs-corner/scouting" className="text-sm text-white/75 print:hidden">← Scouting library</Link><div className="mt-7 flex items-center gap-6"><div className="flex size-28 shrink-0 items-center justify-center rounded-xl bg-white p-3"><Image src={r.logo} alt={`${r.name} logo`} width={112} height={112} className="max-h-full object-contain" /></div><div><p className="text-xs font-bold uppercase tracking-widest text-red-400">Private coach scouting · 2026</p><h1 className="mt-2 text-3xl font-black sm:text-5xl">{r.name}</h1><p className="mt-3 text-sm">Prepared {r.reportDate} · Results through {r.resultsThrough} · Ratings {r.ratingsAsOf}</p></div></div></div></header><div className="site-container space-y-8 py-8">
    <nav aria-label="Report sections" className="flex flex-wrap gap-3 print:hidden">{[['overview','Overview'],['results','Results'],['players','Players'],['preparation','Preparation'],['video','Video to review'],['sources','Sources and gaps']].map(([id,label])=><a key={id} href={`#${id}`} className="rounded-full border bg-white px-4 py-2 text-sm font-semibold">{label}</a>)}</nav>
    <section id="overview"><h2 className="text-2xl font-bold">At a glance</h2><div className="mt-4 grid grid-cols-2 gap-3 md:grid-cols-4">{[['Record',`${r.record.w}–${r.record.l}–${r.record.d}`],['Goals',`${r.record.gf} for · ${r.record.ga} against`],['Per match',`${(r.record.gf/(r.record.w+r.record.l+r.record.d)).toFixed(2)} for · ${(r.record.ga/(r.record.w+r.record.l+r.record.d)).toFixed(2)} against`],['Shutouts',shutouts],['StatsPlus state rank',`#${r.rank} · all divisions`],['Rating',r.rating.toFixed(2)],['Schedule strength',r.sos.toFixed(2)]].map(([label,value])=><div key={label} className="surface-card p-4"><p className="text-xs font-semibold text-muted-foreground">{label}</p><p className="mt-2 font-bold">{value}</p></div>)}</div>{r.conferenceContext && <p className="mt-5 rounded-xl border bg-white p-4 text-sm leading-relaxed">{r.conferenceContext}</p>}<h3 className="mt-6 text-xl font-bold">Assessment</h3><p className="mt-3 max-w-4xl leading-relaxed">{r.assessment}</p></section>
    <section id="results"><h2 className="text-2xl font-bold">Results and schedule</h2><div className="mt-4 overflow-x-auto"><table className="w-full bg-white text-left text-sm"><thead><tr className="border-b"><th className="p-3">Date</th><th className="p-3">Opponent</th><th className="p-3">Result</th></tr></thead><tbody>{r.matches.map((m,i)=><tr key={`${m.date}-${m.opponent}-${i}`} className="border-b"><td className="p-3">{m.date||'Date not supplied'}</td><td className="p-3">{m.opponent}</td><td className="p-3 font-semibold">{m.gf>m.ga?'W':m.gf<m.ga?'L':'T'} {m.gf}–{m.ga}</td></tr>)}</tbody></table></div>{r.upcoming.length>0&&<div className="mt-5"><h3 className="font-bold">Scheduled fixtures · no result entered</h3>{r.upcoming.map(m=><p key={m.date} className="mt-2 text-sm">{m.date} · {m.opponent} · {m.detail}</p>)}</div>}</section>
    <section id="players"><h2 className="text-2xl font-bold">Players to identify</h2><p className="mt-2 text-sm text-muted-foreground">{r.playerSource}. Listed positions do not establish match deployment. — means unavailable.</p><div className="mt-4 overflow-x-auto"><table className="w-full bg-white text-left text-sm"><thead><tr className="border-b">{['No.','Player','Year',r.playerStatsMinimums?'Goals (min.)':'Goals',r.playerStatsMinimums?'Assists (min.)':'Assists','Identification notes'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{r.players.map(p=><tr key={p.name} className="border-b"><td className="p-3 font-bold">{p.number}</td><td className="p-3">{p.name}</td><td className="p-3">{p.year}</td><td className="p-3">{p.goals??'—'}</td><td className="p-3">{p.assists??'—'}</td><td className="p-3">{p.role}</td></tr>)}</tbody></table></div></section>
    <section id="preparation"><h2 className="text-2xl font-bold">Preparation</h2><p className="mt-2 text-sm font-semibold text-primary">Proposed approach · confirm with film</p>{r.approach.map(p=><p key={p} className="mt-4 max-w-4xl leading-relaxed">{p}</p>)}</section>
    <section id="video"><h2 className="text-2xl font-bold">Video to review</h2><p className="mt-2 text-muted-foreground">Linked videos include match broadcasts and labeled highlights; other priorities need team film. No tactical film observations have been verified yet.</p><div className="mt-5 space-y-5">{r.video.map((v,i)=><article key={v.match} className="surface-card p-5"><p className="text-xs font-bold uppercase text-primary">Video priority {i+1} · {v.url ? "video linked" : "film needed"}</p><h3 className="mt-2 text-lg font-bold">{v.match}</h3><p className="mt-3">{v.question}</p>{v.url && <a href={v.url} target="_blank" rel="noreferrer" className="mt-3 inline-block font-semibold text-primary underline">Open video →</a>}<p className="mt-4 text-sm text-muted-foreground">Capture: link · timestamp · player number · observed action · coaching implication.</p></article>)}</div></section>
    <section id="sources"><h2 className="text-2xl font-bold">Sources and gaps</h2>{r.sources.map(s=><p key={s.label} className="mt-3 text-sm">{s.url?<a href={s.url} target="_blank" rel="noreferrer" className="text-primary underline">{s.label}</a>:s.label}</p>)}<ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-muted-foreground">{r.gaps.map(g=><li key={g}>{g}</li>)}</ul></section>
  </div></main></>
}
