import type { Metadata } from "next"
import { PolicyPage } from "@/components/policy-page"
export const metadata: Metadata = { title: "Privacy Policy" }
export default function Page() { return <PolicyPage title="Privacy Policy"><section><h2>Scope and contact</h2><p>Andrew Montalbano operates this independent community Hortonville Boys Soccer website from Hortonville, Wisconsin 54944. This policy describes information handled by this website. For privacy questions, corrections, or removal requests, email <a href="mailto:andrewmmontalbano@gmail.com">andrewmmontalbano@gmail.com</a>. Include the affected page link; do not send identity documents or sensitive student information.</p></section>
<section><h2>Information handled by this site</h2><p>Public pages contain team rosters, names, jersey numbers, results, statistics, historical material, and photographs. Coach tools store player-card drafts, uploaded photos, and coach-written descriptions. Red Room stores player names and tags, roster membership, hashed access keys, session records, game results, trivia attempts, ratings, and preferences. Signing in sends your password or player key to the server for verification. Emailing us sends your email address, message, and attachments through email providers. Recruiting assessment answers are processed in your browser while the page is open; downloading notes saves a file on your device.</p></section>
<section><h2>Purposes and service providers</h2><p>Information supports the archive, team information, authentication, coach tools, game features, and responses to requests. Hosting and database providers process requests and stored records; email providers process correspondence. Hosting and security systems may process IP addresses, request details, and operational logs. The site code does not include advertising pixels or visitor analytics. We do not offer personal information for sale or use it for targeted advertising.</p></section>
<section><h2>Access and retention</h2><p>Public archive information is visible to anyone. Player-card drafts and review copies require coach sign-in. Red Room participants can see game information provided by that feature. Coach sessions expire after 12 hours; Red Room sessions expire after 180 days or end on sign-out. Expiration does not automatically delete account or game records. Archive, account, card, and correspondence records may remain until reviewed or removed; logs and backups follow provider settings. Contact us to request access, correction, or deletion. Legal obligations and backup limitations may affect what can be removed.</p></section>
<section><h2>Children and student information</h2><p>Do not submit information about children under 13 through interactive features. A parent or guardian should contact us with concerns about a child's information or photo. Student publication permissions, school restrictions, and removal requests require individual review. Do not upload grades, medical information, home addresses, dates of birth, or sensitive student records.</p></section>
<section><h2>Your choices and external sites</h2><p>Browse public pages without signing in, sign out of interactive features, and clear browser storage. See the <a href="/cookies">Cookie Policy</a>. Social media, map, and recruiting links lead to services with their own policies. Policy changes will be reflected in this page’s update date.</p></section></PolicyPage> }
