import type { Metadata } from "next"
import { PolicyPage } from "@/components/policy-page"
export const metadata: Metadata = { title: "Terms and Conditions" }
export default function Page() { return <PolicyPage title="Terms and Conditions"><section><h2>Using the site</h2><p>This website provides soccer information, historical resources, recruiting research tools, and restricted team features. Use it lawfully and respectfully. Do not attempt unauthorized access, share private access keys, interfere with the service, or upload material you are not entitled to use.</p></section>
<section><h2>Accuracy and decisions</h2><p>Schedules, statistics, rankings, historical records, and recruiting contacts may be incomplete or change. Verify game arrangements with the team and eligibility, admissions, financial aid, and recruiting requirements with the relevant school or governing organization. Recruiting tools are research starting points; they do not guarantee admission, scholarships, offers, eligibility, or playing time.</p></section>
<section><h2>Photos, documents, and contributions</h2><p>Third-party photographs, logos, and documents remain the property of their respective owners. Their appearance here does not grant permission to reuse them. Before submitting material, confirm copyright permission and any required permission from people depicted, including a parent or guardian for a minor. Contributions are reviewed before publication. Agree the scope of publication permission with the site contact; sending an email does not transfer ownership.</p></section>
<section><h2>Accounts and privacy</h2><p>Use only an account assigned to you. Keep credentials private and report suspected misuse. Do not submit sensitive student information or information about children under 13 through interactive features. The <a href="/privacy">Privacy Policy</a> and <a href="/cookies">Cookie Policy</a> explain information handling.</p></section>
<section><h2>External services and availability</h2><p>External links are provided for reference. The linked service controls its content and privacy practices. Features may be corrected, changed, or unavailable. Nothing on this page limits rights or remedies that applicable law does not allow to be limited.</p></section>
<section><h2>Questions and corrections</h2><p>Report inaccurate content, rights concerns, or access problems to <a href="mailto:andrewmmontalbano@gmail.com">andrewmmontalbano@gmail.com</a>, including the affected page link. These terms may be updated as features change.</p></section></PolicyPage> }
