import type { Metadata } from "next"
import Link from "next/link"
import { cookies } from "next/headers"
import { Navigation } from "@/components/navigation"
import { COACH_COOKIE, validCoachCookie } from "@/lib/coach-auth"
import { scoutingGroup } from "@/lib/scouting"
import { reviewSeeding, type Fixture } from "@/lib/scouting-seeding"
import { CoachLogin } from "../login"
import { Recommendation } from "./recommendation"

export const dynamic="force-dynamic"
export const metadata:Metadata={title:'Seeding Review | Coach’s Corner',robots:{index:false,follow:false,nocache:true}}
const scores=(id:string,matches:Fixture[])=>matches.map(m=>`${m.date}: ${m.a===id?m.ga:m.gb}–${m.a===id?m.gb:m.ga}`).join('; ')
export default async function SeedingReviewPage() {
 if(!validCoachCookie((await cookies()).get(COACH_COOKIE)?.value)) return <><Navigation /><CoachLogin /></>
 const g=scoutingGroup, review=reviewSeeding(g.teams,g.matches,g.cutoff)
 return <><Navigation /><main className="min-h-screen bg-[#f7f7f5] pb-16"><header className="bg-neutral-950 text-white"><div className="site-container py-10"><Link href="/coachs-corner" className="text-sm text-white/75">← Coach’s Corner</Link><h1 className="mt-8 text-4xl font-black">Group B Seeding Review</h1><p className="mt-4 max-w-3xl text-white/75">A defensible recommendation from dated evidence. Apply the same criteria to every team, including Hortonville.</p><p className="mt-4 text-sm">Snapshot retrieved {g.retrievedAt} · Ratings {g.ratingsAsOf} · Cutoff {g.cutoff} · Completed results through October 1</p></div></header><div className="site-container space-y-8 py-8">
 <section><h2 className="text-2xl font-bold">How to use this review</h2><p className="mt-3 leading-relaxed">The starting order is descending StatsPlus rating, an analytical baseline rather than an official seeding formula. Records, schedule strength, direct meetings and shared opponents remain visible for coach review. Ratings already reflect results and opponent strength; adding arbitrary weighted components can count the same evidence twice.</p><p className="mt-3 leading-relaxed">Compare common opponents using 3 points for a win, 1 for a draw and 0 for a loss. Average repeat meetings with each opponent, then weight each shared opponent equally. This is a custom comparison, not an official rule. Goal margins are evidence rather than a sorting bonus. Head-to-head cycles and conflicts require judgment.</p><p className="mt-3 text-sm text-muted-foreground">Conference standings, injuries and availability are not populated in this snapshot. Missing information does not count as a loss. Close rating differences do not establish meaningful separation or win probabilities.</p></section>
 <section><h2 className="text-2xl font-bold">Rating baseline · unofficial</h2><div className="mt-4 overflow-x-auto"><table className="w-full bg-white text-left text-sm"><thead><tr className="border-b">{['Order','Team','Record','Goals','Rating','SOS','Score reconciliation'].map(h=><th className="p-3" key={h}>{h}</th>)}</tr></thead><tbody>{review.records.map((t,i)=><tr className={`border-b ${t.id==='Hortonville'?'bg-red-50':''}`} key={t.id}><td className="p-3">{i+1}</td><td className="p-3 font-bold">{t.name}</td><td className="p-3">{t.record.w}–{t.record.l}–{t.record.d}</td><td className="p-3">{t.record.gf}–{t.record.ga}</td><td className="p-3">{Number.isFinite(t.rating)?t.rating?.toFixed(2):'Missing — review'}</td><td className="p-3">{t.sos.toFixed(2)}</td><td className="p-3">{t.reconciled?'Matches source totals':'Mismatch — review required'}</td></tr>)}</tbody></table></div><p className="mt-3 text-sm text-muted-foreground">Equal ratings use alphabetical display only. All eight teams remain visible, regardless of whether a scouting report is available.</p></section>
 <section><h2 className="text-2xl font-bold">Pairwise evidence</h2><p className="mt-2 text-muted-foreground">Open any comparison to inspect direct scores, shared opponents, and evidence that challenges the baseline.</p><div className="mt-4 space-y-3">{review.pairs.map(p=><details key={`${p.a}-${p.b}`} className="surface-card p-5"><summary className="cursor-pointer font-bold">{p.a} / {p.b}{p.flags.length>0&&<span className="ml-3 text-sm text-primary">Review flags: {p.flags.length}</span>}</summary><p className="mt-4 text-sm">Direct meetings, from {p.a}’s perspective: {scores(p.a,p.direct)||'No completed meeting in snapshot'}</p>{p.flags.map(f=><p className="mt-2 text-sm font-semibold text-primary" key={f}>{f}</p>)}<p className="mt-3 text-sm">Common-opponent average result-points difference ({p.a} minus {p.b}): {p.delta===null?'Unavailable':p.delta.toFixed(3)} · {p.common.length} shared opponents</p>{p.common.length>0&&<div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr><th className="p-2">Opponent</th><th className="p-2">{p.a}</th><th className="p-2">{p.b}</th></tr></thead><tbody>{p.common.map(c=><tr key={c.opponent} className="border-t"><td className="p-2">{c.opponent}</td><td className="p-2">{scores(p.a,c.aScores)} · {c.a.ppg?.toFixed(2)} pts/match</td><td className="p-2">{scores(p.b,c.bScores)} · {c.b.ppg?.toFixed(2)} pts/match</td></tr>)}</tbody></table></div>}</details>)}</div></section>
 <Recommendation teams={review.records.map(t=>t.id)} cutoff={g.cutoff} />
 <section><h2 className="text-2xl font-bold">Meeting results</h2><p className="mt-3">No meeting results have been entered. This snapshot and exported recommendations are unofficial. Final seeds require the actual meeting outcome, resolved ties and any appeals. Later scouting updates must not silently rewrite finalized meeting results.</p></section>
 <section><h2 className="text-2xl font-bold">Sources</h2><p className="mt-3 text-sm">Coach-supplied Group B dataset and standalone analysis, prepared October 3, 2026. Team score totals are recalculated from deduplicated final fixtures.</p><Link href="/coachs-corner/scouting" className="mt-3 inline-block font-bold text-primary underline">Scouting reports and team source links →</Link></section>
 </div></main></>
}
